[font]
size = 15.0

[font.normal]
family = "Terminus"
style = "Regular"

[colors.primary]
background = "#0a0a0a"
foreground = "#ffffff"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 300
blink_timeout = 0
